import time

"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""


def main():
    start = time.time()

    n = 500
    triangle_number = 0
    number_of_divisors = 0
    iterator = 0

    while number_of_divisors < n:
        iterator += 1
        triangle_number += iterator
        number_of_divisors = 0

        for i in range(1, int(triangle_number ** 0.5)):
            if triangle_number % i == 0:
                number_of_divisors += 2

    print("First triangle number to have over five hundred divisors: " + str(triangle_number))

    finish = time.time()

    print("Execution time : " +
          str(finish - start))


if __name__ == "__main__":
    main()
